%YAML:1.0
---
num_cameras: 3
cameras:
   -
      focal: 4.5063124731106464e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.82833087e-01, -1.78550817e-02, 1.83631256e-01,
             6.54772064e-03, 9.98054683e-01, 6.19993657e-02,
             -1.84381038e-01, -5.97326607e-02, 9.81037974e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 4.5063124731106464e+03, 0., 640., 0.,
             4.5063124731106464e+03, 360., 0., 0., 1. ]
   -
      focal: 4.5552195117574320e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.99914229e-01, 1.30843883e-02, -5.31062076e-04,
             -1.30195478e-02, 9.97674406e-01, 6.69049621e-02,
             1.40523631e-03, -6.68923110e-02, 9.97759163e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 4.5552195117574320e+03, 0., 640., 0.,
             4.5552195117574320e+03, 360., 0., 0., 1. ]
   -
      focal: 4.6811698110509487e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.83086348e-01, 3.94274294e-03, -1.83100194e-01,
             6.69636903e-03, 9.98325944e-01, 5.74507900e-02,
             1.83020130e-01, -5.77051975e-02, 9.81414020e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 4.6811698110509487e+03, 0., 640., 0.,
             4.6811698110509487e+03, 360., 0., 0., 1. ]
