%YAML:1.0
---
num_cameras: 3
cameras:
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 6.5067671711900584e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.91376221e-01, -3.49311978e-02, -1.26305535e-01,
             8.73573683e-03, 9.79291379e-01, -2.02266455e-01,
             1.30755395e-01, 1.99418798e-01, 9.71151412e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 6.5067671711900584e+03, 0., 640., 0.,
             6.5067671711900584e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 6.5106635991602552e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.99851584e-01, 1.67689994e-02, -3.95190390e-03,
             -1.72205698e-02, 9.79659438e-01, -1.99926928e-01,
             5.18948073e-04, 1.99965373e-01, 9.79802728e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 6.5106635991602552e+03, 0., 640., 0.,
             6.5106635991602552e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 6.0805273786051002e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.91307199e-01, 1.85273699e-02, 1.30257428e-01,
             8.63265060e-03, 9.78742361e-01, -2.04911053e-01,
             -1.31284878e-01, 2.04254314e-01, 9.70074415e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 6.0805273786051002e+03, 0., 640., 0.,
             6.0805273786051002e+03, 360., 0., 0., 1. ]
