%YAML:1.0
---
# 相机间夹角为75度时的拼接参数
num_cameras: 3
cameras:
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 9.4207918521639403e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.93206441e-01, 4.44923863e-02, -1.07523657e-01,
             -1.59902219e-02, 9.67435181e-01, 2.52613366e-01,
             1.15261555e-01, -2.49177918e-01, 9.61574256e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 9.4207918521639403e+03, 0., 640., 0.,
             9.4207918521639403e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 9.6781797614445986e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.99224782e-01, -3.93475145e-02, 1.26932864e-03,
             3.76468003e-02, 9.64470565e-01, 2.61494428e-01,
             -1.15133915e-02, -2.61243939e-01, 9.65204179e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 9.6781797614445986e+03, 0., 640., 0.,
             9.6781797614445986e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 9.6016457224678124e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.94322419e-01, -5.73455961e-03, 1.06254324e-01,
             -2.18601413e-02, 9.66240108e-01, 2.56714433e-01,
             -1.04139335e-01, -2.57579714e-01, 9.60628867e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 9.6016457224678124e+03, 0., 640., 0.,
             9.6016457224678124e+03, 360., 0., 0., 1. ]
