%YAML:1.0
---
num_cameras: 3
cameras:
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 6.5893996001868754e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.89703119e-01, 4.75077927e-02, 1.35021314e-01,
             2.05353647e-03, 9.38502133e-01, -3.45268041e-01,
             -1.43120721e-01, 3.41990083e-01, 9.28740978e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 6.5893996001868754e+03, 0., 640., 0.,
             6.5893996001868754e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 6.2782317268021443e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.99988317e-01, 4.67009330e-03, 1.27922965e-03,
             -3.95013718e-03, 9.39586878e-01, -3.42288256e-01,
             -2.80046370e-03, 3.42279196e-01, 9.39594328e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 6.2782317268021443e+03, 0., 640., 0.,
             6.2782317268021443e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 6.1499428411096042e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.89295900e-01, -5.21132909e-02, -1.36300549e-01,
             1.93844968e-03, 9.38666642e-01, -3.44821155e-01,
             1.45910546e-01, 3.40865970e-01, 9.28720057e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 6.1499428411096042e+03, 0., 640., 0.,
             6.1499428411096042e+03, 360., 0., 0., 1. ]
