%YAML:1.0
---
num_cameras: 3
cameras:
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 4.1292210802952286e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.74801779e-01, 4.17556986e-02, 2.19130337e-01,
             9.44894552e-03, 9.73714530e-01, -2.27576852e-01,
             -2.22872987e-01, 2.23912895e-01, 9.48783934e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 4.1292210802952286e+03, 0., 640., 0.,
             4.1292210802952286e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 3.7748112025161254e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.99822795e-01, 1.86654851e-02, 2.44224747e-03,
             -1.76649094e-02, 9.75132346e-01, -2.20918968e-01,
             -6.50506932e-03, 2.20836714e-01, 9.75289285e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 3.7748112025161254e+03, 0., 640., 0.,
             3.7748112025161254e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 3.7740128799480076e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.73315060e-01, -5.96945435e-02, -2.21572593e-01,
             8.68262351e-03, 9.74460542e-01, -2.24391669e-01,
             2.29308695e-01, 2.16479987e-01, 9.48975325e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 3.7740128799480076e+03, 0., 640., 0.,
             3.7740128799480076e+03, 360., 0., 0., 1. ]
