%YAML:1.0
---
num_cameras: 3
cameras:
   -
      focal: 1.1266689487663540e+04
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.97237206e-01, 9.80765466e-03, 7.36328959e-02,
             7.46568106e-03, 9.72993910e-01, -2.30710760e-01,
             -7.39070326e-02, 2.30623096e-01, 9.70232487e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 1.1266689487663540e+04, 0., 640., 0.,
             1.1266689487663540e+04, 360., 0., 0., 1. ]
   -
      focal: 1.1240005636585585e+04
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.99896824e-01, 1.43628875e-02, -1.09525710e-04,
             -1.40078701e-02, 9.73439753e-01, -2.28514776e-01,
             -3.17547657e-03, 2.28492722e-01, 9.73540545e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 1.1240005636585585e+04, 0., 640., 0.,
             1.1240005636585585e+04, 360., 0., 0., 1. ]
   -
      focal: 1.1567180585022930e+04
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.97003019e-01, -2.40677726e-02, -7.35233724e-02,
             6.58109738e-03, 9.73316967e-01, -2.29370937e-01,
             7.70820379e-02, 2.28199616e-01, 9.70558405e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 1.1567180585022930e+04, 0., 640., 0.,
             1.1567180585022930e+04, 360., 0., 0., 1. ]
