%YAML:1.0
---
num_cameras: 3
cameras:
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 7.3198210340174310e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.89928365e-01, -7.03905942e-03, -1.41394779e-01,
             2.00640373e-02, 9.95657444e-01, 9.09048617e-02,
             1.40140891e-01, -9.28262100e-02, 9.85770702e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 7.3198210340174310e+03, 0., 640., 0.,
             7.3198210340174310e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 7.0267275087636417e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.99256492e-01, 3.85549180e-02, 1.55259244e-04,
             -3.84166129e-02, 9.95314538e-01, 8.87307003e-02,
             3.26647167e-03, -8.86706710e-02, 9.96055663e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 7.0267275087636417e+03, 0., 640., 0.,
             7.0267275087636417e+03, 360., 0., 0., 1. ]
   -
      FOV_hor: 105.
      FOV_ver: 57.
      focal: 7.5617191560903084e+03
      aspect: 1.
      ppx: 640.
      ppy: 360.
      R: !!opencv-matrix
         rows: 3
         cols: 3
         dt: f
         data: [ 9.89476800e-01, -3.14185992e-02, 1.41239524e-01,
             1.87231228e-02, 9.95735705e-01, 9.03325081e-02,
             -1.43475339e-01, -8.67374539e-02, 9.85845566e-01 ]
      t: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ 0., 0., 0. ]
      K_matrix: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 7.5617191560903084e+03, 0., 640., 0.,
             7.5617191560903084e+03, 360., 0., 0., 1. ]
